spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/weatherdata?reWriteBatchedInserts=true
    username: postgres
    password: changeme
    #    driver-class-name: org.postgresql.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
          lob:
            non_contextual_creation: true
