spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weatherdata
    username: postgres
    password: changeme
    driver-class-name: org.postgresql.Driver

    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true